### ISSUE TITLE
Arreglos simples de front

### ISSUE THREAD

**Issue by mjlescano** [DemocraciaEnRed/bahiablanca#60]
- ¿Cómo funciona?
  - [x] Arreglar link imagen 3
  - [x] Arreglar link imagen 4
- Acerca De
  - [x] Arreglar logo
  - [x] Corregir texto de "¿como se eligieron los proyectos?" 
    - `Los proyectos seleccionados corresponden al Poder Ejecutivo y a cuatro de los bloques del Concejo Deliberante. El plazo para que puedas participar será del 11 de noviembre al 25 de noviembre.`
  - [x] Agregar al final:
    - `Ante cualquier duda duda o sugerencia escribinos a bahiablanca@democracyos.org`
- Layout
  - [x] Agregar en el footer a la derecha:
    - `¿Dudas, sugerencias? escribinos a bahiablanca@democracyos.org`

**Comment by jfresco** [comment]
El punto de `Home` es #58

**Comment by mjlescano** [comment]
Borrado de acá :dancer:

**Comment by jfresco** [comment]
¿Esto se puede cerrar? Es un issue de Heroku.
